### ISSUE TITLE
Queue parameter in pycondor.Job not added to submit file when built by dagman

### ISSUE THREAD

**Issue by mattmeehan** [jrbourbeau/pycondor#38]
When a pycondor.Job that includes the queue parameter is built by a dagman object, the resulting submit file for the job does not contain the input queue parameter.

We do get the desired behavior in this case, when just building the job:
```python
job = pycondor.Job('examplejob', 'examplejob.py',
                          error=error, output=output,
                          log=log, submit=submit, verbose=2,
                          queue=5)
job.build()
```

However, when the job is built by a dagman object, we do not get the desired behavior:

```python
job = pycondor.Job('examplejob', 'examplejob.py',
                          error=error, output=output,
                          log=log, submit=submit, verbose=2,
                          queue=5)
dagman = pycondor.Dagman('exampledagman', submit=submit, verbose=2)
dagman.add_job(job)
dagman.build()
```

It seems to be an issue with the dagman implementation.

**Comment by jrbourbeau** [comment]
@mattmeehan Thanks for submitting this issue! I was able to reproduce the same problem. When `job` in your above example is built it has `queue 5` in it's submit file, but when build from `dagman`, the corresponding `job` submit file only has `queue`. 

It looks like the problem is coming from here

https://github.com/jrbourbeau/pycondor/blob/fc4e1ba5e0a1086e0006f50d87455d14aa0df5e5/pycondor/job.py#L240-L246

Currently, just `queue` is getting added to the lines in the job submit file if it's being built from a `Dagman`. I think it should be something like `lines.append('queue {}'.format(self.queue))` instead. Are you interested in implementing the fix?

**Comment by mattmeehan** [comment]
@jrbourbeau Yeah, I'll implement the fix later today.
